### ISSUE TITLE
Plugin is not visible in the Dropdown of the Constant Editor

### ISSUE THREAD

**Issue by Batman777** [nitsan-technologies/ns_cookiebot#1]
Hello,
I cannot set Domain Group ID because the plugin is not visible in the dropdown of the constant editor. Typo 3 6.2.31
Do you have any ideas? Thank you in advance :-)

**Comment by gabiposch** [comment]
Same problem at my project - I changed typoscriptfile extension to txt - after that i found the file in"Constant Editor" - But still the extension isnt working (typo 6.2). :-(

**Comment by Batman777** [comment]
Tip: If you do not have too much temlplates in your project then I would suggest to use this workaround. Therefore you do not need the ext. anymore.
Typoscript:
page.headTag (
<head>
<script id="Cookiebot" src="https://consent.cookiebot.com/uc.js" data-cbid="YOUR-VERY-LONG-NUMBER" data-blockingmode="auto" type="text/javascript"></script>
)
